<a href="https://colab.research.google.com/github/PRANEETHASRK/machinelearing/blob/main/CSE20001_LAB5_machinelearing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
np.random.seed(42)

from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split

from sklearn.metrics import classification_report,confusion_matrix


### A1

In [3]:
def sigmoid (x):
    return 1/(1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

In [4]:
#Input datasets
inputs = np.array([[0,0],[0,1],[1,0],[1,1]])
expected_output = np.array([[0],[0],[0],[1]])

epochs = 1000
lr = 0.05
inputLayerNeurons, hiddenLayerNeurons, outputLayerNeurons = 2,2,1

In [5]:
#Random weights and bias initialization
hidden_weights = np.random.uniform(size=(inputLayerNeurons,hiddenLayerNeurons))
hidden_bias =np.random.uniform(size=(1,hiddenLayerNeurons))
output_weights = np.random.uniform(size=(hiddenLayerNeurons,outputLayerNeurons))
output_bias = np.random.uniform(size=(1,outputLayerNeurons))

print("Initial hidden weights: ",end='')
print(*hidden_weights)
print("Initial hidden biases: ",end='')
print(*hidden_bias)
print("Initial output weights: ",end='')
print(*output_weights)
print("Initial output biases: ",end='')
print(*output_bias)

Initial hidden weights: [0.37454012 0.95071431] [0.73199394 0.59865848]
Initial hidden biases: [0.15601864 0.15599452]
Initial output weights: [0.05808361] [0.86617615]
Initial output biases: [0.60111501]


In [7]:
#Training algorithm

In [6]:
for epoch in range(epochs):
#Forward Propagation
    hidden_layer_activation = np.dot(inputs,hidden_weights)
    hidden_layer_activation += hidden_bias
    hidden_layer_output = sigmoid(hidden_layer_activation)

    output_layer_activation = np.dot(hidden_layer_output,output_weights)
    output_layer_activation += output_bias
    predicted_output = sigmoid(output_layer_activation)
#Backpropagation
    error = np.square(expected_output - predicted_output)/2
    d_predicted_output = error * sigmoid_derivative(predicted_output)

    error_hidden_layer = d_predicted_output.dot(output_weights.T)
    d_hidden_layer = error_hidden_layer * sigmoid_derivative(hidden_layer_output)

#Updating Weights and Biases
    output_weights += hidden_layer_output.T.dot(d_predicted_output) * lr
    output_bias += np.sum(d_predicted_output,axis=0,keepdims=True) * lr
    hidden_weights += inputs.T.dot(d_hidden_layer) * lr
    hidden_bias += np.sum(d_hidden_layer,axis=0,keepdims=True) * lr
    
    print("\n")
    print("_____EPOCH",epoch+1)
    print("\n hidden weights: ",end='')
    print(*hidden_weights)
    print("hidden bias: ",end='')
    print(*hidden_bias)
    print("output weights: ",end='')
    print(*output_weights)
    print("output bias: ",end='')
    print(*output_bias)
    
    avg_error=abs(np.average(error))
    print("The average error after Epoch",epoch+1,"is",avg_error)
    
    if avg_error<=0.002:
        break


print("\n Final hidden weights: ",end='')
print(*hidden_weights)
print("Final hidden bias: ",end='')
print(*hidden_bias)
print("Final output weights: ",end='')
print(*output_weights)
print("Final output bias: ",end='')
print(*output_bias)

if avg_error<=0.002:
    print("\n CONVERGING AT Epoch",epoch+1,"is",*predicted_output,end='')
else:
    print("\n Output from neural network after 1,000 epochs: ",end='')
    print(*predicted_output)
    


Streaming output truncated to the last 5000 lines.
_____EPOCH 446

 hidden weights: [0.42392144 1.04675204] [0.77639473 0.71665111]
hidden bias: [0.32156287 0.55177865]
output weights: [0.97283987] [1.86156407]
output bias: [2.04044232]
The average error after Epoch 446 is 0.3624155158669314


_____EPOCH 447

 hidden weights: [0.42399307 1.04683991] [0.77645781 0.71676138]
hidden bias: [0.32182052 0.55220067]
output weights: [0.9736286] [1.86244365]
output bias: [2.04164407]
The average error after Epoch 447 is 0.36244723835388


_____EPOCH 448

 hidden weights: [0.42406458 1.04692757] [0.77652078 0.71687138]
hidden bias: [0.32207774 0.55262181]
output weights: [0.97441549] [1.8633212]
output bias: [2.04284293]
The average error after Epoch 448 is 0.3624788117796281


_____EPOCH 449

 hidden weights: [0.42413595 1.04701502] [0.77658362 0.71698113]
hidden bias: [0.32233453 0.55304205]
output weights: [0.97520056] [1.86419674]
output bias: [2.04403892]
The average error after Epoch 449 i

### A2

In [8]:
#Input datasets
inputs = np.array([[0,0],[0,1],[1,0],[1,1]])
expected_output = np.array([[0],[1],[1],[0]])

epochs = 1000
lr = 0.05
inputLayerNeurons, hiddenLayerNeurons, outputLayerNeurons = 2,2,1

In [9]:
#Random weights and bias initialization
hidden_weights = np.random.uniform(size=(inputLayerNeurons,hiddenLayerNeurons))
hidden_bias =np.random.uniform(size=(1,hiddenLayerNeurons))
output_weights = np.random.uniform(size=(hiddenLayerNeurons,outputLayerNeurons))
output_bias = np.random.uniform(size=(1,outputLayerNeurons))

print("Initial hidden weights: ",end='')
print(*hidden_weights)
print("Initial hidden biases: ",end='')
print(*hidden_bias)
print("Initial output weights: ",end='')
print(*output_weights)
print("Initial output biases: ",end='')
print(*output_bias)

Initial hidden weights: [0.70807258 0.02058449] [0.96990985 0.83244264]
Initial hidden biases: [0.21233911 0.18182497]
Initial output weights: [0.18340451] [0.30424224]
Initial output biases: [0.52475643]


##### Training algorithm

In [10]:
for epoch in range(epochs):
#Forward Propagation
    hidden_layer_activation = np.dot(inputs,hidden_weights)
    hidden_layer_activation += hidden_bias
    hidden_layer_output = sigmoid(hidden_layer_activation)

    output_layer_activation = np.dot(hidden_layer_output,output_weights)
    output_layer_activation += output_bias
    predicted_output = sigmoid(output_layer_activation)
#Backpropagation
    error = expected_output - predicted_output
    d_predicted_output = error * sigmoid_derivative(predicted_output)

    error_hidden_layer = d_predicted_output.dot(output_weights.T)
    d_hidden_layer = error_hidden_layer * sigmoid_derivative(hidden_layer_output)

#Updating Weights and Biases
    output_weights += hidden_layer_output.T.dot(d_predicted_output) * lr
    output_bias += np.sum(d_predicted_output,axis=0,keepdims=True) * lr
    hidden_weights += inputs.T.dot(d_hidden_layer) * lr
    hidden_bias += np.sum(d_hidden_layer,axis=0,keepdims=True) * lr
    
    print("\n")
    print("_____EPOCH",epoch+1)
    print("\n hidden weights: ",end='')
    print(*hidden_weights)
    print("hidden bias: ",end='')
    print(*hidden_bias)
    print("output weights: ",end='')
    print(*output_weights)
    print("output bias: ",end='')
    print(*output_bias)
    
    avg_error=abs(np.average(error))
    print("The average error after Epoch",epoch+1,"is",avg_error)
    
    if avg_error<=0.002:
        break

print("\n Final hidden weights: ",end='')
print(*hidden_weights)
print("Final hidden bias: ",end='')
print(*hidden_bias)
print("Final output weights: ",end='')
print(*output_weights)
print("Final output bias: ",end='')
print(*output_bias)

if avg_error<=0.002:
    print("\n CONVERGING AT Epoch",epoch+1,"is",*predicted_output,end='')
else:
    print("\n Output from neural network after 1,000 epochs: ",end='')
    print(*predicted_output)
    
    



Streaming output truncated to the last 5000 lines.
_____EPOCH 446

 hidden weights: [0.69637532 0.01775563] [0.96104115 0.82530254]
hidden bias: [0.20714918 0.1658278 ]
output weights: [-0.01450143] [-0.0097625]
output bias: [0.0278293]
The average error after Epoch 446 is 0.0027814163731254282


_____EPOCH 447

 hidden weights: [0.69636741 0.01775259] [0.9610354  0.82530255]
hidden bias: [0.20714753 0.16582803]
output weights: [-0.01424193] [-0.00984272]
output bias: [0.02769032]
The average error after Epoch 447 is 0.0027807941514444157


_____EPOCH 448

 hidden weights: [0.69635964 0.01774953] [0.96102976 0.82530256]
hidden bias: [0.2071459  0.16582826]
output weights: [-0.01398246] [-0.00992294]
output bias: [0.02755138]
The average error after Epoch 448 is 0.002780175747935487


_____EPOCH 449

 hidden weights: [0.69635201 0.01774644] [0.96102422 0.82530257]
hidden bias: [0.20714431 0.1658285 ]
output weights: [-0.013723] [-0.01000317]
output bias: [0.02741246]
The average error a

### A3

##### AND GATE

In [11]:
#Input datasets
inputs = np.array([[0,0],[0,1],[1,0],[1,1]])
expected_output = np.array([[1,0],[1,0],[1,0],[0,1]])

epochs = 1000
lr = 0.05
inputLayerNeurons, hiddenLayerNeurons, outputLayerNeurons = 2,2,2

In [12]:
#Random weights and bias initialization
hidden_weights = np.random.uniform(size=(inputLayerNeurons,hiddenLayerNeurons))
hidden_bias =np.random.uniform(size=(1,hiddenLayerNeurons))
output_weights = np.random.uniform(size=(hiddenLayerNeurons,outputLayerNeurons))
output_bias = np.random.uniform(size=(1,outputLayerNeurons))

print("Initial hidden weights: ",end='')
print(*hidden_weights)
print("Initial hidden biases: ",end='')
print(*hidden_bias)
print("Initial output weights: ",end='')
print(*output_weights)
print("Initial output biases: ",end='')
print(*output_bias)

Initial hidden weights: [0.43194502 0.29122914] [0.61185289 0.13949386]
Initial hidden biases: [0.29214465 0.36636184]
Initial output weights: [0.45606998 0.78517596] [0.19967378 0.51423444]
Initial output biases: [0.59241457 0.04645041]


### Training 

In [13]:
for epoch in range(epochs):
#Forward Propagation
    hidden_layer_activation = np.dot(inputs,hidden_weights)
    hidden_layer_activation += hidden_bias
    hidden_layer_output = sigmoid(hidden_layer_activation)

    output_layer_activation = np.dot(hidden_layer_output,output_weights)
    output_layer_activation += output_bias
    predicted_output = sigmoid(output_layer_activation)
#Backpropagation
    error = expected_output - predicted_output
    d_predicted_output = error * sigmoid_derivative(predicted_output)

    error_hidden_layer = d_predicted_output.dot(output_weights.T)
    d_hidden_layer = error_hidden_layer * sigmoid_derivative(hidden_layer_output)

#Updating Weights and Biases
    output_weights += hidden_layer_output.T.dot(d_predicted_output) * lr
    output_bias += np.sum(d_predicted_output,axis=0,keepdims=True) * lr
    hidden_weights += inputs.T.dot(d_hidden_layer) * lr
    hidden_bias += np.sum(d_hidden_layer,axis=0,keepdims=True) * lr
    
    print("\n")
    print("_____EPOCH",epoch+1)
    print("\n hidden weights: ",end='')
    print(*hidden_weights)
    print("hidden bias: ",end='')
    print(*hidden_bias)
    print("output weights: ",end='')
    print(*output_weights)
    print("output bias: ",end='')
    print(*output_bias)
    
    avg_error=abs(np.average(error))
    print("The average error after Epoch",epoch+1,"is",avg_error)
    
    if avg_error<=0.002:
        break

print("\n Final hidden weights: ",end='')
print(*hidden_weights)
print("Final hidden bias: ",end='')
print(*hidden_bias)
print("Final output weights: ",end='')
print(*output_weights)
print("Final output bias: ",end='')
print(*output_bias)

if avg_error<=0.002:
    print("\n CONVERGING AT Epoch",epoch+1,"is",*predicted_output,end='')
else:
    print("\n Output from neural network after 1,000 epochs: ",end='')
    print(*predicted_output)
    


Streaming output truncated to the last 5000 lines.
_____EPOCH 446

 hidden weights: [0.39415842 0.16295144] [0.57436314 0.01278443]
hidden bias: [0.18052079 0.33930301]
output weights: [0.17180803 0.40761954] [ 0.19033437 -0.11094711]
output bias: [ 0.8269023  -1.21665137]
The average error after Epoch 446 is 0.0037346154938188644


_____EPOCH 447

 hidden weights: [0.39433102 0.16262631] [0.57453811 0.0124667 ]
hidden bias: [0.18041233 0.33934667]
output weights: [0.17109081 0.4083289 ] [ 0.19038724 -0.11100817]
output bias: [ 0.82732269 -1.21708942]
The average error after Epoch 447 is 0.003732199281464524


_____EPOCH 448

 hidden weights: [0.39450463 0.16230099] [0.57471411 0.01214877]
hidden bias: [0.18030322 0.33939028]
output weights: [0.17037316 0.4090388 ] [ 0.19044069 -0.1110697 ]
output bias: [ 0.8277429 -1.2175271]
The average error after Epoch 448 is 0.0037298219327468254


_____EPOCH 449

 hidden weights: [0.39467925 0.16197547] [0.57489115 0.01183066]
hidden bias: [0.180

#### XOR GATE

In [14]:
#Input datasets
inputs = np.array([[0,0],[0,1],[1,0],[1,1]])
expected_output = np.array([[1,0],[0,1],[0,1],[1,0]])

epochs = 1000
lr = 0.05
inputLayerNeurons, hiddenLayerNeurons, outputLayerNeurons = 2,2,2

In [15]:
#Random weights and bias initialization
hidden_weights = np.random.uniform(size=(inputLayerNeurons,hiddenLayerNeurons))
hidden_bias =np.random.uniform(size=(1,hiddenLayerNeurons))
output_weights = np.random.uniform(size=(hiddenLayerNeurons,outputLayerNeurons))
output_bias = np.random.uniform(size=(1,outputLayerNeurons))

print("Initial hidden weights: ",end='')
print(*hidden_weights)
print("Initial hidden biases: ",end='')
print(*hidden_bias)
print("Initial output weights: ",end='')
print(*output_weights)
print("Initial output biases: ",end='')
print(*output_bias)

Initial hidden weights: [0.60754485 0.17052412] [0.06505159 0.94888554]
Initial hidden biases: [0.96563203 0.80839735]
Initial output weights: [0.30461377 0.09767211] [0.68423303 0.44015249]
Initial output biases: [0.12203823 0.49517691]


In [16]:
for epoch in range(epochs):
#Forward Propagation
    hidden_layer_activation = np.dot(inputs,hidden_weights)
    hidden_layer_activation += hidden_bias
    hidden_layer_output = sigmoid(hidden_layer_activation)

    output_layer_activation = np.dot(hidden_layer_output,output_weights)
    output_layer_activation += output_bias
    predicted_output = sigmoid(output_layer_activation)
#Backpropagation
    error = expected_output - predicted_output
    d_predicted_output = error * sigmoid_derivative(predicted_output)

    error_hidden_layer = d_predicted_output.dot(output_weights.T)
    d_hidden_layer = error_hidden_layer * sigmoid_derivative(hidden_layer_output)

#Updating Weights and Biases
    output_weights += hidden_layer_output.T.dot(d_predicted_output) * lr
    output_bias += np.sum(d_predicted_output,axis=0,keepdims=True) * lr
    hidden_weights += inputs.T.dot(d_hidden_layer) * lr
    hidden_bias += np.sum(d_hidden_layer,axis=0,keepdims=True) * lr
    
    
    print("\n")
    print("_____EPOCH",epoch+1)
    print("\n hidden weights: ",end='')
    print(*hidden_weights)
    print("hidden bias: ",end='')
    print(*hidden_bias)
    print("output weights: ",end='')
    print(*output_weights)
    print("output bias: ",end='')
    print(*output_bias)
    
    avg_error=abs(np.average(error))
    print("The average error after Epoch",epoch+1,"is",avg_error)
    
    if avg_error<=0.002:
        break

print("\n Final hidden weights: ",end='')
print(hidden_weights)
print("Final hidden bias: ",end='')
print(*hidden_bias)
print("Final output weights: ",end='')
print(*output_weights)
print("Final output bias: ",end='')
print(*output_bias)

if avg_error<=0.002:
     print("\n CONVERGING AT Epoch",epoch+1,"is",*predicted_output,end='')
else:
    print("\n Output from neural network after 1,000 epochs: ",end='')
    print(*predicted_output)




_____EPOCH 1

 hidden weights: [0.60728542 0.16964261] [0.0646925  0.94827079]
hidden bias: [0.96505199 0.80683496]
output weights: [0.29782346 0.09085791] [0.67733463 0.43334323]
output bias: [0.1134183  0.48641959]
The average error after Epoch 1 is 0.21244017709516938


_____EPOCH 2

 hidden weights: [0.60703684 0.16877678] [0.06434564 0.94766786]
hidden bias: [0.96449762 0.80530704]
output weights: [0.29110943 0.0841166 ] [0.67051407 0.42660875]
output bias: [0.10489404 0.47775445]
The average error after Epoch 2 is 0.20840863081490077


_____EPOCH 3

 hidden weights: [0.60679896 0.16792677] [0.06401087 0.94707687]
hidden bias: [0.96396855 0.80381372]
output weights: [0.28447452 0.07745104] [0.66377417 0.41995193]
output bias: [0.09646914 0.46918527]
The average error after Epoch 3 is 0.2043904814096913


_____EPOCH 4

 hidden weights: [0.60657164 0.16709267] [0.063688   0.94649791]
hidden bias: [0.96346436 0.80235508]
output weights: [0.27792139 0.07086398] [0.65711759 0.4133754

### A4

### AND gate 

In [17]:
df=pd.read_excel('/content/andgate.xlsx')

In [18]:
print(df)

   x  y  output
0  0  0       0
1  0  1       0
2  1  0       0
3  1  1       1


In [19]:
df['output'].unique()

array([0, 1])

In [20]:
x= df.drop('output',axis=1)
y=df['output']
print(x.head(2))
print(y.head(4))

   x  y
0  0  0
1  0  1
0    0
1    0
2    0
3    1
Name: output, dtype: int64


#### Splitting and training

In [21]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
print(x_train.shape)
print(x_test.shape)

(3, 2)
(1, 2)


In [22]:
x_test

x  y
0  0  0

In [23]:
x_train

x  y
1  0  1
3  1  1
2  1  0

In [24]:
mlp=MLPClassifier(hidden_layer_sizes=(3,2),max_iter=10,activation='relu')

In [25]:
mlp.fit(x_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


MLPClassifier(hidden_layer_sizes=(3, 2), max_iter=10)

#### Testing

In [26]:
pred=mlp.predict(x_test)
pred

array([1])

#### Modal evaluation

In [37]:
confusion_matrix(y_test,pred)

array([[0, 1],
       [0, 0]])

In [38]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       1.0
           1       0.00      0.00      0.00       0.0

    accuracy                           0.00       1.0
   macro avg       0.00      0.00      0.00       1.0
weighted avg       0.00      0.00      0.00       1.0



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1

### XOR gate

In [54]:
df=pd.read_excel('/content/XOR.xlsx')

In [55]:
print(df)

   X0  X1  X2  Z
0   1   0   0  0
1   1   0   1  1
2   1   1   0  1
3   1   1   1  0


In [57]:
df['Z'].unique()

array([0, 1])

In [58]:
x= df.drop('Z',axis=1)
y=df['Z']
print(x.head(2))
print(y.head(4))

   X0  X1  X2
0   1   0   0
1   1   0   1
0    0
1    1
2    1
3    0
Name: Z, dtype: int64


#### Splitting and training

In [42]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
print(x_train.shape)
print(x_test.shape)

(3, 2)
(1, 2)


In [43]:
x_test

x  y
1  0  1

In [44]:
x_train

x  y
3  1  1
2  1  0
0  0  0

In [45]:
mlp=MLPClassifier(hidden_layer_sizes=(3,2),max_iter=10,activation='relu')

In [46]:
mlp.fit(x_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


MLPClassifier(hidden_layer_sizes=(3, 2), max_iter=10)

#### Testing

In [47]:
pred=mlp.predict(x_test)
pred

array([1])

#### Modal evaluation

In [48]:
confusion_matrix(y_test,pred)

array([[0, 1],
       [0, 0]])

In [49]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       1.0
           1       0.00      0.00      0.00       0.0

    accuracy                           0.00       1.0
   macro avg       0.00      0.00      0.00       1.0
weighted avg       0.00      0.00      0.00       1.0



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1

### A5

In [74]:
df=pd.read_excel('/content/up123.xlsx')
df

District Name  No. OfVillagesWhere SurveyCompleted  Banks      %    ATM  \
0         All India                               648358  74639  11.51  47910   
1       State Total                               103064   9679   9.39   5195   
2        AGRA (118)                                  942    114  12.10     81   
3     ALIGARH (119)                                 1167     89   7.63     49   
4   ALLAHABAD (120)                                 2877    341  11.85    231   
..              ...                                  ...    ...    ...    ...   
72    Kasganj (633)                                  654     65   9.94     27   
73     Amethi (640)                                  985    117  11.88     67   
74    SAMBHAL (659)                                 1117    136  12.18     32   
75     SHAMLI (660)                                  320     43  13.44     22   
76      HAPUR (661)                                  327     63  19.27     40   

      %.1  Connected to All weather road    %.2  \
0    7.39                         443734  68.44   
1    5.04                          80153  77.77   
2    8.60                            815  86.52   
3    4.20                            893  76.52   
4    8.03                           1903  66.15   
..    ...                            ...    ...   
72   4.13                            570  87.16   
73   6.80                            793  80.51   
74   2.86                            796  71.26   
75   6.88                            291  90.94   
76  12.23                            300  91.74   

    Internal Pucca Roads (Cc/ Brick Road)    %.3  ...  Govt. Seed centre  \
0                                  438576  67.64  ...              54474   
1                                   84751  82.23  ...               6430   
2                                     770  81.74  ...                 82   
3                                     999  85.60  ...                 69   
4                                    2244  78.00  ...                195   
..                                    ...    ...  ...                ...   
72                                    590  90.21  ...                 42   
73                                    861  87.41  ...                 64   
74                                    962  86.12  ...                 82   
75                                    296  92.50  ...                 19   
76                                    300  91.74  ...                 26   

    %.20  Fertilizer Shop   %.21  Community waste disposal system   %.22  \
0   8.40            95533  14.73                           102392  15.79   
1   6.24            10869  10.55                            13512  13.11   
2   8.70               99  10.51                              148  15.71   
3   5.91              106   9.08                              122  10.45   
4   6.78              353  12.27                              553  19.22   
..   ...              ...    ...                              ...    ...   
72  6.42               77  11.77                              102  15.60   
73  6.50              113  11.47                              142  14.42   
74  7.34              107   9.58                              149  13.34   
75  5.94               44  13.75                              150  46.88   
76  7.95               48  14.68                               53  16.21   

    Community bio gas or recycle of waste for production use  %.23  \
0                                               38775         5.98   
1                                                2527         2.45   
2                                                  23         2.44   
3                                                  44         3.77   
4                                                 137         4.76   
..                                                ...          ...   
72                                                 25         3.82   
73                                

In [75]:
df3=df['Banks']> 500
df4=df3.replace(to_replace=True,value='High')
df5=df4.replace(to_replace=False,value='Low')

In [76]:
df['classify']=df5

In [77]:
df

District Name  No. OfVillagesWhere SurveyCompleted  Banks      %    ATM  \
0         All India                               648358  74639  11.51  47910   
1       State Total                               103064   9679   9.39   5195   
2        AGRA (118)                                  942    114  12.10     81   
3     ALIGARH (119)                                 1167     89   7.63     49   
4   ALLAHABAD (120)                                 2877    341  11.85    231   
..              ...                                  ...    ...    ...    ...   
72    Kasganj (633)                                  654     65   9.94     27   
73     Amethi (640)                                  985    117  11.88     67   
74    SAMBHAL (659)                                 1117    136  12.18     32   
75     SHAMLI (660)                                  320     43  13.44     22   
76      HAPUR (661)                                  327     63  19.27     40   

      %.1  Connected to All weather road    %.2  \
0    7.39                         443734  68.44   
1    5.04                          80153  77.77   
2    8.60                            815  86.52   
3    4.20                            893  76.52   
4    8.03                           1903  66.15   
..    ...                            ...    ...   
72   4.13                            570  87.16   
73   6.80                            793  80.51   
74   2.86                            796  71.26   
75   6.88                            291  90.94   
76  12.23                            300  91.74   

    Internal Pucca Roads (Cc/ Brick Road)    %.3  ...  %.20  Fertilizer Shop  \
0                                  438576  67.64  ...  8.40            95533   
1                                   84751  82.23  ...  6.24            10869   
2                                     770  81.74  ...  8.70               99   
3                                     999  85.60  ...  5.91              106   
4                                    2244  78.00  ...  6.78              353   
..                                    ...    ...  ...   ...              ...   
72                                    590  90.21  ...  6.42               77   
73                                    861  87.41  ...  6.50              113   
74                                    962  86.12  ...  7.34              107   
75                                    296  92.50  ...  5.94               44   
76                                    300  91.74  ...  7.95               48   

     %.21  Community waste disposal system   %.22  \
0   14.73                           102392  15.79   
1   10.55                            13512  13.11   
2   10.51                              148  15.71   
3    9.08                              122  10.45   
4   12.27                              553  19.22   
..    ...                              ...    ...   
72  11.77                              102  15.60   
73  11.47                              142  14.42   
74   9.58                              149  13.34   
75  13.75                              150  46.88   
76  14.68                               53  16.21   

    Community bio gas or recycle of waste for production use  %.23  \
0                                               38775         5.98   
1                                                2527         2.45   
2                                                  23         2.44   
3                                                  44         3.77   
4                                                 137         4.76   
..                                                ...          ...   
72                                                 25         3.82   
73                                                 20         2.03   
74                                                 17         1.52   
75                                                 16         5.00   
76                                                 1

In [78]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
print(x_train.shape)
print(x_test.shape)

(3, 3)
(1, 3)


### MLP Classification for training and testing non-linear sepearble data .

In [79]:
mlp=MLPClassifier(hidden_layer_sizes=(3,2),max_iter=10,activation='relu')
mlp

MLPClassifier(hidden_layer_sizes=(3, 2), max_iter=10)

In [80]:
mlp.fit(x_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


MLPClassifier(hidden_layer_sizes=(3, 2), max_iter=10)

## Testing

In [81]:
pred=mlp.predict(x_test)
pred

array([0])

### Modal evaluation    , (contains confusion matrix and classifcation report)

#### Confusion Matrix

In [82]:
confusion_matrix(y_test,pred)


array([[0, 0],
       [1, 0]])

#### Classification Report

In [83]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       0.0
           1       0.00      0.00      0.00       1.0

    accuracy                           0.00       1.0
   macro avg       0.00      0.00      0.00       1.0
weighted avg       0.00      0.00      0.00       1.0



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1